# .scrutinizer.yml
version: 1

# Define the extensions needed, in this case PHP
extensions:
    - php

# Define the files and directories to be excluded from analysis
filter:
    # Exclude non-package files and directories
    exclude:
        - "tests/*"
        - "public/*"
        - "resources/*"
        - "vendor/*"
        - "node_modules/*"
        - "database/*"
        - "storage/*"
        - "config/*"
        - "routes/*"
        - "app/Http/Controllers/*"
        - "app/Http/Requests/*"
        - "bootstrap/*"

# Optional: Set up the tools for analyzing your package's code
tools:
    php:
        # Define the paths to the PHP codebase
        paths:
            - "src"
        # Optional: Enable PHPUnit analysis if you have tests
        # tests:
        #     paths:
        #         - "tests"

# Optional: Configure checks for quality score
checks:
    style: true
    complexity: true
    consistency: true
    security: true
