# .scrutinizer.yml
version: 1

# Exclude non-relevant files and directories from the analysis
exclude:
    - "/tests/*"
    - "/public/*"
    - "/resources/*"
    - "/vendor/*"
    - "/node_modules/*"
    - "/database/*"
    - "/storage/*"
    - "/app/Http/Controllers/*"
    - "/app/Http/Requests/*"
    - "/config/*"
    - "/routes/*"
    - "/bootstrap/*"

# Define the language of the package
language: php

# Define analysis settings for your Laravel package
analyzers:
    php:
        paths:
            - "src"
        
        # Optional: if you are using PHPUnit, include your test directory here
        # tests:
        #     paths:
        #         - "tests"
    
# Optional: Set a minimum quality score if you want Scrutinizer to help you track improvements
quality:
    score: 75
