# .scrutinizer.yml
version: '1'

# Define the build environment (using PHP 8.1 for example)
build:
    image: php:8.1

# Enable the necessary extensions for your project (in this case PHP)
extensions:
    php: true

# Define the files to be excluded from analysis
filter:
    exclude:
        - "/tests/*"
        - "/public/*"
        - "/resources/*"
        - "/vendor/*"
        - "/node_modules/*"
        - "/database/*"
        - "/storage/*"
        - "/config/*"
        - "/routes/*"
        - "/app/Http/Controllers/*"
        - "/app/Http/Requests/*"
        - "/bootstrap/*"

# Define which tools should be used for analysis
tools:
    php:
        paths:
            - "src"

# Optional: Define conditions under which a build failure occurs (e.g., low score)
build_failure_conditions:
    score: 70

# Optional: You can define credentials for any private dependencies (if needed)
credentials: {}
