# .scrutinizer.yml
version: '1'

# Define the build environment (set PHP version here)
build:
    image: php:8.1

# Define which extensions to use (in this case, PHP analysis)
extensions:
    php: true

# Define which files to include/exclude for analysis
filter:
    exclude:
        - "/tests/*"
        - "/public/*"
        - "/resources/*"
        - "/vendor/*"
        - "/node_modules/*"
        - "/database/*"
        - "/storage/*"
        - "/config/*"
        - "/routes/*"
        - "/app/Http/Controllers/*"
        - "/app/Http/Requests/*"
        - "/bootstrap/*"

# Enable checks for code quality
checks:
    style: true
    complexity: true
    consistency: true
    security: true

# Optional: Specify coding style rules if you want to enforce specific coding standards
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true

# Optional: Define conditions under which a build failure occurs (e.g., low score)
build_failure_conditions:
    score: 70

# Set up tools to analyze your PHP code
tools:
    php:
        paths:
            - "src"

# Optional: Define credentials for any private dependencies (if needed)
credentials: {}
