# .scrutinizer.yml
version: '1'

# Define the build environment and PHP version
build:
    image: php:8.1

# Set up the extensions you want to use (In this case, PHP analysis)
extensions:
    - php

# Filter to exclude unnecessary directories/files (like tests, public, etc.)
filter:
    exclude:
        - "/tests/*"
        - "/public/*"
        - "/resources/*"
        - "/vendor/*"
        - "/node_modules/*"
        - "/database/*"
        - "/storage/*"
        - "/config/*"
        - "/routes/*"
        - "/app/Http/Controllers/*"
        - "/app/Http/Requests/*"
        - "/bootstrap/*"

# Optional: Configure the tools for analyzing the PHP package
tools:
    php:
        paths:
            - "src"

# Optional: You can set a quality score threshold if you want to enforce a minimum quality score
quality:
    score: 75
